console.log('##############################################')
console.log(' どーもーココロヤミです')
console.log(' そんなにこのサイトの仕組みが知りたいの？')
console.log(' ↓ ここにコードがあるから、Starつけてよね❤️')
console.log(' https://github.com/yuki540net/DropOut')
console.log('##############################################')
